---
title: "Covid Cases in R"
output:
  html_document:
    df_print: paged
---
# Covid-19 Kaynaklı En Fazla Ölümün Olduğu 25 Ülke

```{r include=FALSE}

library(httr)
library(readxl)
library(RCurl) #Bir link çalışmazsa diğer linki çalıştıracak bir kod var burada.

# http://memosisland.blogspot.com/2012/03/check-url-existance-with-r.html

url2 <- paste("https://opendata.ecdc.europa.eu/covid19/casedistribution/csv")
GET(url2, write_disk(tf<-tempfile(fileext = ".csv")))

df=read.csv((tf))
```



```{r message=FALSE, warning=FALSE, paged.print=FALSE}
covid_death_total <- sum(df$deaths)
covid_cases_total <- sum(df$cases)

covid_death_top <- aggregate(x = df$deaths,
          by = list(df$countriesAndTerritories),              
          FUN = sum) 

covid_death_top_25 <- covid_death_top[order(-covid_death_top$x),]

head(covid_death_top_25,n=25)

```

Dünya genelinde Covid-19 tespit edilen vaka sayısı `r covid_cases_total` olmuştur. `Sys.Date()`.

Dünya genelinde Covid-19'dan ölen toplam kişi sayısı `r covid_death_total` olmuştur. `Sys.Date()`.

The features we have are: `r names(df)`.

```{r}
library(dplyr)
library(DT)
edf <- df %>% group_by(countriesAndTerritories) %>% mutate(deathRate = sum(deaths)/sum(cases))

datatable(
edf[,c(1,5,6,7,11)], extensions = 'Buttons', options = list(
dom = 'Bfrtip',
buttons = c('copy', 'csv', 'excel', 'pdf', 'print')
)
)

```

# Grafikler

```{r}
library(ggplot2)

edf %>% filter(deaths > 50) %>%
group_by(countriesAndTerritories) %>%
summarise(Cases_Total = sum(cases), Deaths_Total = sum(deaths)) %>%
ggplot(aes(countriesAndTerritories)) +
geom_point(aes(y = Cases_Total, color = "yellow")) +
geom_point(aes(y = Deaths_Total, color = "red")) +
coord_flip()
```

#Türkiye İstatistikleri

```{r}

library(Hmisc)

data <- read.csv("C:/Users/SATELLITE/Desktop/Covid_R/covid_19_data_tr.csv", stringsAsFactors = FALSE)

describe(data)


```

```{r}

library(lubridate)
data$Last_Update <- mdy(data$Last_Update)

# alternative
# data <- data %>%
# mutate(days = dmy(Last_Update))

```
#Türkiye Grafikleri

```{r}
base <- ggplot(data = data, aes(x=Last_Update, 
                                y="Toplam Kisi Sayısı",group=1,)) +
  geom_line(aes(y = Deaths), color="black",size=0.8, linetype="dashed") + 
  geom_line(aes(y = Recovered), color="steelblue",size=0.8, linetype = "twodash")
base + scale_x_date(date_breaks = "3 days", date_labels = "%b %d")
```

